### ISSUE TITLE
Transfer ownership...?

### ISSUE THREAD

**Issue by wndxlori** [ijpiantanida/bacon-expect#4]
It be possible for you to transfer this repository to the new RubyMotion Community?

https://github.com/rubymotion-community

Then we can get it up to date and working with current stuff.

We'd also need access to push the gem (you can assign that to me, lori@wndx.com)

**Comment by ijpiantanida** [comment]
Hi @wndxlori, this gem is not being used a lot, so I'd rather you fork the project and publish it under a different name instead of transferring it.

I can then link to the new project from this repo.
